### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by radekj** [collective/collective.referencedatagridfield#1]
Hi,

I need one small fix that is already commited to the trunk (bb5282c8b17a4ee10711b50759bf479f06f353ab) to make the referencedatagridfield work properely using archetypes.schemaextender and becouse I need it on a production instance it would be nice not to rely on the trunk version, so I would be very grateful for preparing a new release with this change.

Thanks!

**Comment by kroman0** [comment]
Released http://pypi.python.org/pypi/collective.referencedatagridfield
